from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def _source(relative_path):
    return (ROOT / relative_path).read_text(encoding="utf-8")


def test_segmentation_toolbox_has_tooltips_for_generate_and_derive_tabs():
    source = _source("HRpQCTTools/SegmentationHRpQCT/SegmentationHRpQCT.py")

    for snippet in [
        "Input volume used to generate masks and bone segmentation.",
        "Laplace-Hamming threshold in native Scanco attenuation units.",
        "Run contour and segmentation generation with the selected methods and expert settings.",
    ]:
        assert snippet in source


def test_scanco_io_has_import_export_tooltips():
    source = _source("IOTools/ScancoIO/ScancoIO.py")

    for snippet in [
        "Load Scanco images as editable scalar volumes, segmentations from nonzero voxels, or geometry transforms.",
        "The volume name updates when this path changes.",
        "Unit convention for grayscale export.",
        "Editable Scanco processing-log fields",
        "Write the selected Slicer volume, labelmap, or segmentation to a Scanco AIM file.",
    ]:
        assert snippet in source


def test_motion_score_has_run_review_and_retrain_tooltips():
    source = _source("HRpQCTTools/MotionScoreHRpQCT/MotionScoreHRpQCT.py")

    for snippet in [
        "Start manual review immediately for scans already discovered or processed.",
        "Stop the active prediction, review-preparation, or training process.",
        "Choose whether the review queue shows pending, all, or low-confidence scans.",
        "Build the retraining manifest from manual grades and selected AI-only labels.",
        "Training-curve plot generated by the latest retraining run.",
    ]:
        assert snippet in source


def test_timelapsed_has_control_level_tooltips_for_profiles_analysis_and_loading():
    source = _source("HRpQCTTools/TimelapsedHRpQCT/TimelapsedHRpQCT.py")

    for snippet in [
        "Apply the selected profile to visible settings",
        "Adjust absolute density-change threshold",
        "Load the selected processed output into the current Slicer scene.",
        "Apply the current remodelling analysis options to the loaded comparison.",
    ]:
        assert snippet in source
