from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def _source(relative_path):
    return (ROOT / relative_path).read_text(encoding="utf-8")


def test_segmentation_toolbox_has_tooltips_for_generate_and_derive_tabs():
    source = _source("HRpQCTTools/SegmentationHRpQCT/SegmentationHRpQCT.py")

    for snippet in [
        "Input HR-pQCT volume used to generate masks and bone segmentation.",
        "Laplace-Hamming threshold in native Scanco attenuation units.",
        "Create full, trabecular, or cortical mask from the other two compartment masks.",
        "Create one material labelmap from bone segmentation plus any two compartment masks.",
        "Check full/trab/cort consistency",
        "Report nonzero voxel counts",
    ]:
        assert snippet in source


def test_scanco_io_has_import_export_tooltips():
    source = _source("IOTools/ScancoIO/ScancoIO.py")

    for snippet in [
        "Load Scanco images as editable scalar volumes, segmentations from nonzero voxels, or geometry transforms.",
        "The volume name updates when this path changes.",
        "Unit convention for grayscale export.",
        "Editable Scanco processing-log fields",
        "Write the selected Slicer volume, labelmap, or segmentation to a Scanco AIM file.",
    ]:
        assert snippet in source


def test_motion_score_has_run_review_and_retrain_tooltips():
    source = _source("HRpQCTTools/MotionScoreHRpQCT/MotionScoreHRpQCT.py")

    for snippet in [
        "Start manual review immediately for scans already discovered or processed.",
        "Read the next AIM in the background so grading can advance more smoothly.",
        "Choose whether the review queue shows pending, all, or low-confidence scans.",
        "Build the retraining manifest from manual grades and selected AI-only labels.",
        "Training-curve plot generated by the latest retraining run.",
    ]:
        assert snippet in source


def test_timelapsed_has_control_level_tooltips_for_profiles_analysis_and_loading():
    source = _source("HRpQCTTools/TimelapsedHRpQCT/TimelapsedHRpQCT.py")

    for snippet in [
        "Apply the selected profile to visible settings",
        "Adjust absolute density-change threshold",
        "Load existing pairwise cohort analysis rows from disk.",
        "Load the selected processed output into the current Slicer scene.",
        "Apply current analysis options to the selected loaded remodelling image.",
    ]:
        assert snippet in source
